# Generated by Django 3.1.2 on 2020-10-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name_plural': 'problems'},
        ),
        migrations.AlterField(
            model_name='problem',
            name='p_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
