# Generated by Django 3.1.2 on 2020-10-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20201031_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='p_C',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='p_D',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='p_E',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
